# Generated by Django 4.2 on 2023-05-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
                ('image', models.CharField(max_length=200, verbose_name='изображение')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата выпуска')),
                ('lte_exists', models.BooleanField(blank=True, null=True, verbose_name='LTE в наличии')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
            ],
        ),
    ]
